Refactor error handling in CI workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,45 +64,57 @@ jobs:
         run: |
           dotnet test "$env:GITHUB_WORKSPACE\VLimat.Eduz.App\VLimat.Eduz.App.Test\VLimat.Eduz.App.Test.csproj" -c Release --no-build --logger "trx;LogFileName=TestResults.trx"
           $testExitCode = $LASTEXITCODE
+          Write-Host "dotnet test exit code = $testExitCode"
 
           dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
           $sonarExitCode = $LASTEXITCODE
+          Write-Host "sonarscanner end exit code = $sonarExitCode"
 
           if ($sonarExitCode -ne 0) {
+            Write-Error "SonarQube end failed."
             exit $sonarExitCode
           }
 
-          exit $testExitCode
+          if ($testExitCode -ne 0) {
+            Write-Error "Tests failed."
+            exit $testExitCode
+          }
 
       - name: Build Docker Image
+        if: success()
         shell: powershell
         run: |
           docker build -t vlimat-backend:new .
 
       - name: Stop Existing Container
+        if: success()
         shell: powershell
         continue-on-error: true
         run: |
           docker stop vlimat-backend
 
       - name: Remove Existing Container
+        if: success()
         shell: powershell
         continue-on-error: true
         run: |
           docker rm vlimat-backend
 
       - name: Remove Existing Image
+        if: success()
         shell: powershell
         continue-on-error: true
         run: |
           docker rmi vlimat-backend
 
       - name: Tag New Image
+        if: success()
         shell: powershell
         run: |
           docker tag vlimat-backend:new vlimat-backend
 
       - name: Run Docker Container
+        if: success()
         shell: powershell
         run: |
           docker run -d --restart unless-stopped -p 5000:8080 --name vlimat-backend vlimat-backend
